#!/usr/bin/env python3

import argparse
import json
import struct
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_IWAD = REPO_ROOT / "src" / "doom1.wad"
OUTPUT_IWAD = REPO_ROOT / "src" / "doom1-arena.wad"
MAP_BLUEPRINTS_DIR = REPO_ROOT / "scripts" / "map_blueprints"
TACTICAL_MAP_BLUEPRINT = MAP_BLUEPRINTS_DIR / "duel_e1m8.json"
OUTPUT_TACTICAL_MAP = REPO_ROOT / "src" / "assets" / "duel_room_layout.svg"

SVG_WIDTH = 512
SVG_HEIGHT = 384
SVG_ROOM_X = 40
SVG_ROOM_Y = 30
SVG_ROOM_WIDTH = 432
SVG_ROOM_HEIGHT = 324


def load_geometry_blueprint() -> dict:
    return json.loads(TACTICAL_MAP_BLUEPRINT.read_text(encoding="utf-8"))


def blueprint_bounds(blueprint: dict) -> dict:
    bounds = blueprint["bounds"]
    return {
        "x_min": int(bounds["x_min"]),
        "x_max": int(bounds["x_max"]),
        "y_min": int(bounds["y_min"]),
        "y_max": int(bounds["y_max"]),
    }


def obstacle_rect(obstacle: dict) -> tuple[int, int, int, int]:
    half_width = int(obstacle["width"]) // 2
    half_height = int(obstacle["height"]) // 2
    center_x = int(obstacle["x"])
    center_y = int(obstacle["y"])
    return (
        center_x - half_width,
        center_y - half_height,
        center_x + half_width,
        center_y + half_height,
    )


def wall_obstacles(blueprint: dict) -> list[dict]:
    return [
        obstacle for obstacle in blueprint.get("obstacles", [])
        if obstacle.get("kind") == "wall"
    ]


def svg_x(bounds: dict, value: int) -> float:
    span = max(1, bounds["x_max"] - bounds["x_min"])
    return SVG_ROOM_X + ((value - bounds["x_min"]) / span) * SVG_ROOM_WIDTH


def svg_y(bounds: dict, value: int) -> float:
    span = max(1, bounds["y_max"] - bounds["y_min"])
    return SVG_ROOM_Y + (1 - ((value - bounds["y_min"]) / span)) * SVG_ROOM_HEIGHT


def fmt(value: float) -> str:
    return f"{value:.3f}".rstrip("0").rstrip(".")


def write_tactical_map_svg(blueprint: dict) -> None:
    bounds = blueprint_bounds(blueprint)
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 384" fill="none">',
        "  <!-- Generated by scripts/generate_duel_room_wad.py from scripts/map_blueprints/duel_e1m8.json. -->",
        '  <rect width="512" height="384" rx="12" fill="#0f1413"/>',
        '  <rect x="40" y="30" width="432" height="324" fill="#141b19" stroke="#d7e0d8" stroke-width="4"/>',
    ]

    for obstacle in wall_obstacles(blueprint):
        left, bottom, right, top = obstacle_rect(obstacle)
        rect_x = svg_x(bounds, left)
        rect_y = svg_y(bounds, top)
        rect_width = svg_x(bounds, right) - rect_x
        rect_height = svg_y(bounds, bottom) - rect_y
        center_x = svg_x(bounds, (left + right) // 2)
        room_top_y = SVG_ROOM_Y
        room_bottom_y = SVG_ROOM_Y + SVG_ROOM_HEIGHT
        obstacle_top_y = rect_y
        obstacle_bottom_y = rect_y + rect_height

        lines.append(
            '  <rect x="{x}" y="{y}" width="{width}" height="{height}" fill="#7b8b84" stroke="#d7e0d8" stroke-width="4"/>'.format(
                x=fmt(rect_x),
                y=fmt(rect_y),
                width=fmt(rect_width),
                height=fmt(rect_height),
            )
        )
        if obstacle_top_y > room_top_y:
            lines.append(
                '  <line x1="{x}" y1="{y1}" x2="{x}" y2="{y2}" stroke="#b3c3bc" stroke-dasharray="8 8" stroke-opacity=".45"/>'.format(
                    x=fmt(center_x),
                    y1=fmt(room_top_y),
                    y2=fmt(obstacle_top_y),
                )
            )
        if obstacle_bottom_y < room_bottom_y:
            lines.append(
                '  <line x1="{x}" y1="{y1}" x2="{x}" y2="{y2}" stroke="#b3c3bc" stroke-dasharray="8 8" stroke-opacity=".45"/>'.format(
                    x=fmt(center_x),
                    y1=fmt(obstacle_bottom_y),
                    y2=fmt(room_bottom_y),
                )
            )
        lines.append(
            '  <text x="{x}" y="{y}" fill="#e3ece4" font-family="system-ui, sans-serif" font-size="16">Wall</text>'.format(
                x=fmt(rect_x - 17),
                y=fmt(rect_y + rect_height / 2 + 14),
            )
        )

    lines.extend(
        [
            '  <text x="58" y="58" fill="#8ea79b" font-family="system-ui, sans-serif" font-size="18">Custom duel room</text>',
            "</svg>",
            "",
        ]
    )
    OUTPUT_TACTICAL_MAP.parent.mkdir(parents=True, exist_ok=True)
    temp_path = OUTPUT_TACTICAL_MAP.with_suffix(".svg.tmp")
    temp_path.write_text("\n".join(lines), encoding="utf-8")
    temp_path.replace(OUTPUT_TACTICAL_MAP)
    print(f"Wrote {OUTPUT_TACTICAL_MAP}")


def build_blockmap(bounds: dict, num_lines: int) -> bytes:
    block_origin_x = bounds["x_min"]
    block_origin_y = bounds["y_min"]
    block_width = (bounds["x_max"] - bounds["x_min"]) // 128
    block_height = (bounds["y_max"] - bounds["y_min"]) // 128
    offsets_count = block_width * block_height
    line_list = list(range(num_lines)) + [-1]
    list_offset = 4 + offsets_count
    offsets = [list_offset] * offsets_count

    return struct.pack(
        "<" + "h" * (4 + len(offsets) + len(line_list)),
        block_origin_x,
        block_origin_y,
        block_width,
        block_height,
        *offsets,
        *line_list,
    )


def seg_angle(v1, v2) -> int:
    dx = v2.x - v1.x
    dy = v2.y - v1.y
    if dx > 0 and dy == 0:
        return 0
    if dx < 0 and dy == 0:
        return 32768
    if dx == 0 and dy > 0:
        return 16384
    if dx == 0 and dy < 0:
        return 49152
    if dx > 0 and dy > 0:
        return 8192
    if dx < 0 and dy > 0:
        return 24576
    if dx < 0 and dy < 0:
        return 40960
    return 57344


def deathmatch_start(Thing, x: int, y: int, angle: int):
    thing = Thing(x=x, y=y, angle=angle, type=11)
    thing.easy = 1
    thing.medium = 1
    thing.hard = 1
    thing.multiplayer = 1
    return thing


def player_start(Thing, x: int, y: int, angle: int, player_num: int):
    thing = Thing(x=x, y=y, angle=angle, type=player_num)
    thing.easy = 1
    thing.medium = 1
    thing.hard = 1
    thing.multiplayer = 1
    return thing


def build_wad(blueprint: dict) -> None:
    from omg import Lump, MapEditor, Seg, Sidedef, SubSector, Vertex, WAD
    from omg.mapedit import Linedef

    bounds = blueprint_bounds(blueprint)
    spawns = blueprint.get("spawns", {})
    player_1_spawn = spawns.get("player_1", {"x": -640, "y": 520, "angle_deg": 0})
    player_2_spawn = spawns.get("player_2", {"x": 640, "y": 520, "angle_deg": 180})

    editor = MapEditor()
    wall_sidedef = Sidedef(tx_mid="STARTAN3", tx_up="-", tx_low="-")
    editor.draw_sector(
        [
            (bounds["x_min"], bounds["y_min"]),
            (bounds["x_max"], bounds["y_min"]),
            (bounds["x_max"], bounds["y_max"]),
            (bounds["x_min"], bounds["y_max"]),
        ],
        sidedef=wall_sidedef,
    )

    for obstacle in wall_obstacles(blueprint):
        left, bottom, right, top = obstacle_rect(obstacle)
        obstacle_start = len(editor.vertexes)
        sidedef_start = len(editor.sidedefs)
        editor.vertexes.extend(
            [
                Vertex(left, bottom),
                Vertex(right, bottom),
                Vertex(right, top),
                Vertex(left, top),
            ]
        )

        for _ in range(4):
            editor.sidedefs.append(Sidedef(tx_mid="STARTAN3", tx_up="-", tx_low="-", sector=0))

        for offset in range(4):
            editor.linedefs.append(
                Linedef(
                    vx_a=obstacle_start + offset,
                    vx_b=obstacle_start + ((offset + 1) % 4),
                    front=sidedef_start + offset,
                    back=Linedef.NONE,
                    flags=1,
                )
            )

    editor.things.extend(
        [
            player_start(Thing, int(player_1_spawn["x"]), int(player_1_spawn["y"]), int(player_1_spawn["angle_deg"]), 1),
            player_start(Thing, int(player_2_spawn["x"]), int(player_2_spawn["y"]), int(player_2_spawn["angle_deg"]), 2),
            player_start(Thing, -320, -520, 0, 3),
            player_start(Thing, 320, -520, 180, 4),
            deathmatch_start(Thing, -768, -512, 45),
            deathmatch_start(Thing, 768, -512, 135),
            deathmatch_start(Thing, 768, 512, 225),
            deathmatch_start(Thing, -768, 512, 315),
        ]
    )

    editor.segs = []
    for line_index, linedef in enumerate(editor.linedefs):
        v1 = editor.vertexes[linedef.vx_a]
        v2 = editor.vertexes[linedef.vx_b]
        editor.segs.append(
            Seg(
                vx_a=linedef.vx_a,
                vx_b=linedef.vx_b,
                angle=seg_angle(v1, v2),
                line=line_index,
                side=0,
                offset=0,
            )
        )

    editor.ssectors = [SubSector(numsegs=len(editor.segs), seg_a=0)]
    editor.nodes = []
    editor.reject = Lump(b"\x00")
    editor.blockmap = Lump(build_blockmap(bounds, len(editor.linedefs)))

    wad = WAD(str(SOURCE_IWAD))
    wad.maps["E1M8"] = editor.to_lumps()
    wad.to_file(str(OUTPUT_IWAD))
    print(f"Wrote {OUTPUT_IWAD}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Doom duel WAD assets from the shared map blueprint.")
    parser.add_argument(
        "--svg-only",
        action="store_true",
        help="Only regenerate the tactical map SVG. Does not require the omg WAD package.",
    )
    args = parser.parse_args()
    blueprint = load_geometry_blueprint()

    write_tactical_map_svg(blueprint)
    if not args.svg_only:
        build_wad(blueprint)


if __name__ == "__main__":
    main()
