#!/usr/bin/env python3

import argparse
import struct
from pathlib import Path
import os

from doom_arena_map_blueprints import ascii_cell_rect, load_geometry_blueprint


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_IWAD = REPO_ROOT / "src" / "doom1.wad"
OUTPUT_IWAD = Path(os.environ.get("DOOM_ARENA_OUTPUT_IWAD", str(REPO_ROOT / "src" / "doom1-arena.wad")))
OUTPUT_TACTICAL_MAP = REPO_ROOT / "src" / "assets" / "duel_room_layout.svg"

SVG_ROOM_X = 40
SVG_ROOM_Y = 30
SVG_ROOM_WIDTH = 432
SVG_ROOM_HEIGHT = 324


def blueprint_bounds(blueprint: dict) -> dict:
    bounds = blueprint["bounds"]
    return {
        "x_min": int(bounds["x_min"]),
        "x_max": int(bounds["x_max"]),
        "y_min": int(bounds["y_min"]),
        "y_max": int(bounds["y_max"]),
    }


def obstacle_rect(obstacle: dict) -> tuple[int, int, int, int]:
    bounds = obstacle.get("bounds")
    if bounds:
        return int(bounds["x_min"]), int(bounds["y_min"]), int(bounds["x_max"]), int(bounds["y_max"])
    half_width = int(obstacle["width"]) // 2
    half_height = int(obstacle["height"]) // 2
    center_x = int(obstacle["x"])
    center_y = int(obstacle["y"])
    return center_x - half_width, center_y - half_height, center_x + half_width, center_y + half_height


def wall_obstacles(blueprint: dict) -> list[dict]:
    return [obstacle for obstacle in blueprint.get("obstacles", []) if obstacle.get("kind") == "wall"]


def svg_x(bounds: dict, value: int) -> float:
    span = max(1, bounds["x_max"] - bounds["x_min"])
    return SVG_ROOM_X + ((value - bounds["x_min"]) / span) * SVG_ROOM_WIDTH


def svg_y(bounds: dict, value: int) -> float:
    span = max(1, bounds["y_max"] - bounds["y_min"])
    return SVG_ROOM_Y + (1 - ((value - bounds["y_min"]) / span)) * SVG_ROOM_HEIGHT


def fmt(value: float) -> str:
    return f"{value:.3f}".rstrip("0").rstrip(".")


def write_tactical_map_svg(blueprint: dict) -> None:
    bounds = blueprint_bounds(blueprint)
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 384" fill="none">',
        "  <!-- Generated by scripts/generate_duel_room_wad.py from scripts/map_blueprints/duel_e1m8_ascii.txt. -->",
        '  <rect width="512" height="384" rx="12" fill="#0f1413"/>',
        '  <rect x="40" y="30" width="432" height="324" fill="#141b19" stroke="#d7e0d8" stroke-width="4"/>',
    ]

    for obstacle in wall_obstacles(blueprint):
        left, bottom, right, top = obstacle_rect(obstacle)
        rect_x = svg_x(bounds, left)
        rect_y = svg_y(bounds, top)
        rect_width = svg_x(bounds, right) - rect_x
        rect_height = svg_y(bounds, bottom) - rect_y
        lines.append(
            '  <rect x="{x}" y="{y}" width="{width}" height="{height}" fill="#7b8b84" stroke="#d7e0d8" stroke-width="4"/>'.format(
                x=fmt(rect_x), y=fmt(rect_y), width=fmt(rect_width), height=fmt(rect_height)
            )
        )

    lines.extend([
        '  <text x="58" y="58" fill="#8ea79b" font-family="system-ui, sans-serif" font-size="18">Custom duel room</text>',
        "</svg>",
        "",
    ])
    OUTPUT_TACTICAL_MAP.parent.mkdir(parents=True, exist_ok=True)
    try:
        OUTPUT_TACTICAL_MAP.write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote {OUTPUT_TACTICAL_MAP}")
    except PermissionError as exc:
        print(f"Skipped {OUTPUT_TACTICAL_MAP}: {exc}")


def build_blockmap(bounds: dict, num_lines: int) -> bytes:
    block_origin_x = bounds["x_min"]
    block_origin_y = bounds["y_min"]
    block_width = max(1, (bounds["x_max"] - bounds["x_min"]) // 128)
    block_height = max(1, (bounds["y_max"] - bounds["y_min"]) // 128)
    offsets_count = block_width * block_height
    line_list = list(range(num_lines)) + [-1]
    list_offset = 4 + offsets_count
    offsets = [list_offset] * offsets_count
    return struct.pack(
        "<" + "h" * (4 + len(offsets) + len(line_list)),
        block_origin_x, block_origin_y, block_width, block_height, *offsets, *line_list,
    )


def seg_angle(v1, v2) -> int:
    dx = v2.x - v1.x
    dy = v2.y - v1.y
    if dx > 0 and dy == 0:
        return 0
    if dx < 0 and dy == 0:
        return 32768
    if dx == 0 and dy > 0:
        return 16384
    if dx == 0 and dy < 0:
        return 49152
    if dx > 0 and dy > 0:
        return 8192
    if dx < 0 and dy > 0:
        return 24576
    if dx < 0 and dy < 0:
        return 40960
    return 57344


def deathmatch_start(Thing, x: int, y: int, angle: int):
    thing = Thing(x=x, y=y, angle=angle, type=11)
    thing.easy = 1
    thing.medium = 1
    thing.hard = 1
    thing.multiplayer = 1
    return thing


def player_start(Thing, x: int, y: int, angle: int, player_num: int):
    thing = Thing(x=x, y=y, angle=angle, type=player_num)
    thing.easy = 1
    thing.medium = 1
    thing.hard = 1
    thing.multiplayer = 1
    return thing


def add_common_things(editor, Thing, spawns: dict) -> None:
    player_1_spawn = spawns.get("player_1", {"x": -608, "y": 544, "angle_deg": 0})
    player_2_spawn = spawns.get("player_2", {"x": 672, "y": 544, "angle_deg": 180})
    editor.things.extend([
        player_start(Thing, int(player_1_spawn["x"]), int(player_1_spawn["y"]), int(player_1_spawn["angle_deg"]), 1),
        player_start(Thing, int(player_2_spawn["x"]), int(player_2_spawn["y"]), int(player_2_spawn["angle_deg"]), 2),
        player_start(Thing, -320, -520, 0, 3),
        player_start(Thing, 320, -520, 180, 4),
        deathmatch_start(Thing, -768, -512, 45),
        deathmatch_start(Thing, 768, -512, 135),
        deathmatch_start(Thing, 768, 512, 225),
        deathmatch_start(Thing, -768, 512, 315),
    ])


def finish_editor(editor, bounds: dict, WAD, Lump, Seg, SubSector) -> None:
    editor.segs = []
    for line_index, linedef in enumerate(editor.linedefs):
        v1 = editor.vertexes[linedef.vx_a]
        v2 = editor.vertexes[linedef.vx_b]
        editor.segs.append(Seg(vx_a=linedef.vx_a, vx_b=linedef.vx_b, angle=seg_angle(v1, v2), line=line_index, side=0, offset=0))
    editor.ssectors = [SubSector(numsegs=len(editor.segs), seg_a=0)]
    editor.nodes = []
    editor.reject = Lump(b"\x00")
    editor.blockmap = Lump(build_blockmap(bounds, len(editor.linedefs)))
    wad = WAD(str(SOURCE_IWAD))
    wad.maps["E1M8"] = editor.to_lumps()
    wad.to_file(str(OUTPUT_IWAD))
    print(f"Wrote {OUTPUT_IWAD}")


def build_wad(blueprint: dict) -> None:
    from omg import Lump, MapEditor, Node, Seg, Sidedef, SubSector, WAD
    from omg.mapedit import Linedef, Thing

    bounds = blueprint_bounds(blueprint)
    rows = [row for row in blueprint.get("ascii_map", "").splitlines() if row]
    if rows:
        row_count = len(rows)
        col_count = len(rows[0])
        cell_size = int(blueprint.get("cell_size", 64))
        editor = MapEditor()
        wall_sidedef = Sidedef(tx_mid="STARTAN3", tx_up="-", tx_low="-")
        for row_index, row in enumerate(rows):
            for col_index, char in enumerate(row):
                if char == "#":
                    continue
                left, bottom, right, top = ascii_cell_rect(row_index, col_index, row_count, col_count, cell_size)
                editor.draw_sector(
                    [
                        (left, bottom),
                        (right, bottom),
                        (right, top),
                        (left, top),
                    ],
                    sidedef=wall_sidedef,
                )
        add_common_things(editor, Thing, blueprint.get("spawns", {}))
        finish_editor(editor, bounds, WAD, Lump, Seg, SubSector)
        return

    obstacles = sorted(wall_obstacles(blueprint), key=lambda item: obstacle_rect(item)[0])
    if len(obstacles) > 2:
        print("Warning: current WAD generator uses only the first two connected wall components.")
        obstacles = obstacles[:2]

    editor = MapEditor()
    wall_sidedef = Sidedef(tx_mid="STARTAN3", tx_up="-", tx_low="-")

    if not obstacles:
        editor.draw_sector(
            [
                (bounds["x_min"], bounds["y_min"]),
                (bounds["x_max"], bounds["y_min"]),
                (bounds["x_max"], bounds["y_max"]),
                (bounds["x_min"], bounds["y_max"]),
            ],
            sidedef=wall_sidedef,
        )
        add_common_things(editor, Thing, blueprint.get("spawns", {}))
        finish_editor(editor, bounds, WAD, Lump, Seg, SubSector)
        return

    if len(obstacles) == 1:
        wall_left, wall_bottom, wall_right, wall_top = obstacle_rect(obstacles[0])
        editor.draw_sector(
            [
                (bounds["x_min"], bounds["y_min"]),
                (wall_left, bounds["y_min"]),
                (wall_left, wall_bottom),
                (wall_left, wall_top),
                (wall_left, bounds["y_max"]),
                (bounds["x_min"], bounds["y_max"]),
            ],
            sidedef=wall_sidedef,
        )
        editor.draw_sector(
            [
                (wall_right, bounds["y_min"]),
                (bounds["x_max"], bounds["y_min"]),
                (bounds["x_max"], bounds["y_max"]),
                (wall_right, bounds["y_max"]),
                (wall_right, wall_top),
                (wall_right, wall_bottom),
            ],
            sidedef=wall_sidedef,
        )
        editor.draw_sector(
            [
                (wall_left, wall_top),
                (wall_right, wall_top),
                (wall_right, bounds["y_max"]),
                (wall_left, bounds["y_max"]),
            ],
            sidedef=wall_sidedef,
        )
        editor.draw_sector(
            [
                (wall_left, bounds["y_min"]),
                (wall_right, bounds["y_min"]),
                (wall_right, wall_bottom),
                (wall_left, wall_bottom),
            ],
            sidedef=wall_sidedef,
        )
        add_common_things(editor, Thing, blueprint.get("spawns", {}))
        build_partitioned_wad(editor, bounds, WAD, Lump, Node, Seg, SubSector, Linedef, [(wall_left, wall_bottom, wall_right, wall_top)])
        return

    w1_left, w1_bottom, w1_right, w1_top = obstacle_rect(obstacles[0])
    w2_left, w2_bottom, w2_right, w2_top = obstacle_rect(obstacles[1])
    wall_bottom = min(w1_bottom, w2_bottom)
    wall_top = max(w1_top, w2_top)

    editor.draw_sector(
        [
            (bounds["x_min"], bounds["y_min"]),
            (w1_left, bounds["y_min"]),
            (w1_left, wall_bottom),
            (w1_left, wall_top),
            (w1_left, bounds["y_max"]),
            (bounds["x_min"], bounds["y_max"]),
        ],
        sidedef=wall_sidedef,
    )
    editor.draw_sector(
        [
            (w1_right, bounds["y_min"]),
            (w2_left, bounds["y_min"]),
            (w2_left, wall_bottom),
            (w2_left, wall_top),
            (w2_left, bounds["y_max"]),
            (w1_right, bounds["y_max"]),
            (w1_right, wall_top),
            (w1_right, wall_bottom),
        ],
        sidedef=wall_sidedef,
    )
    editor.draw_sector(
        [
            (w2_right, bounds["y_min"]),
            (bounds["x_max"], bounds["y_min"]),
            (bounds["x_max"], bounds["y_max"]),
            (w2_right, bounds["y_max"]),
            (w2_right, wall_top),
            (w2_right, wall_bottom),
        ],
        sidedef=wall_sidedef,
    )
    editor.draw_sector(
        [(w1_left, wall_top), (w1_right, wall_top), (w1_right, bounds["y_max"]), (w1_left, bounds["y_max"])],
        sidedef=wall_sidedef,
    )
    editor.draw_sector(
        [(w1_left, bounds["y_min"]), (w1_right, bounds["y_min"]), (w1_right, wall_bottom), (w1_left, wall_bottom)],
        sidedef=wall_sidedef,
    )
    editor.draw_sector(
        [(w2_left, wall_top), (w2_right, wall_top), (w2_right, bounds["y_max"]), (w2_left, bounds["y_max"])],
        sidedef=wall_sidedef,
    )
    editor.draw_sector(
        [(w2_left, bounds["y_min"]), (w2_right, bounds["y_min"]), (w2_right, wall_bottom), (w2_left, wall_bottom)],
        sidedef=wall_sidedef,
    )

    add_common_things(editor, Thing, blueprint.get("spawns", {}))
    build_partitioned_wad(editor, bounds, WAD, Lump, Node, Seg, SubSector, Linedef, [
        (w1_left, wall_bottom, w1_right, wall_top),
        (w2_left, wall_bottom, w2_right, wall_top),
    ])
def build_partitioned_wad(editor, bounds: dict, WAD, Lump, Node, Seg, SubSector, Linedef, walls: list[tuple[int, int, int, int]]) -> None:
    sector_segs = [[] for _ in editor.sectors]
    for line_index, linedef in enumerate(editor.linedefs):
        if linedef.front != Linedef.NONE:
            sector_index = editor.sidedefs[linedef.front].sector
            v1 = editor.vertexes[linedef.vx_a]
            v2 = editor.vertexes[linedef.vx_b]
            sector_segs[sector_index].append(
                Seg(vx_a=linedef.vx_a, vx_b=linedef.vx_b, angle=seg_angle(v1, v2), line=line_index, side=0, offset=0)
            )
        if linedef.back != Linedef.NONE:
            sector_index = editor.sidedefs[linedef.back].sector
            v1 = editor.vertexes[linedef.vx_b]
            v2 = editor.vertexes[linedef.vx_a]
            sector_segs[sector_index].append(
                Seg(vx_a=linedef.vx_b, vx_b=linedef.vx_a, angle=seg_angle(v1, v2), line=line_index, side=1, offset=0)
            )

    editor.segs = []
    editor.ssectors = []
    for segs in sector_segs:
        seg_start = len(editor.segs)
        editor.segs.extend(segs)
        editor.ssectors.append(SubSector(numsegs=len(segs), seg_a=seg_start))

    if len(walls) == 1:
        wall_left, wall_bottom, wall_right, wall_top = walls[0]
        split_y = (wall_bottom + wall_top) // 2
        editor.nodes = [
            Node(
                x_start=wall_left,
                y_start=split_y,
                x_vector=wall_right - wall_left,
                y_vector=0,
                right_bbox_top=wall_bottom,
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=wall_left,
                right_bbox_right=wall_right,
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=wall_top,
                left_bbox_left=wall_left,
                left_bbox_right=wall_right,
                right_index=0x8000 | 3,
                left_index=0x8000 | 2,
            ),
            Node(
                x_start=wall_right,
                y_start=bounds["y_min"],
                x_vector=0,
                y_vector=bounds["y_max"] - bounds["y_min"],
                right_bbox_top=bounds["y_max"],
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=wall_right,
                right_bbox_right=bounds["x_max"],
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=bounds["y_min"],
                left_bbox_left=wall_left,
                left_bbox_right=wall_right,
                right_index=0x8000 | 1,
                left_index=0,
            ),
            Node(
                x_start=wall_left,
                y_start=bounds["y_min"],
                x_vector=0,
                y_vector=bounds["y_max"] - bounds["y_min"],
                right_bbox_top=bounds["y_max"],
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=wall_left,
                right_bbox_right=bounds["x_max"],
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=bounds["y_min"],
                left_bbox_left=bounds["x_min"],
                left_bbox_right=wall_left,
                right_index=1,
                left_index=0x8000 | 0,
            ),
        ]
    else:
        w1_left, wall_bottom, w1_right, wall_top = walls[0]
        w2_left, _wall_bottom, w2_right, _wall_top = walls[1]
        split_y = (wall_bottom + wall_top) // 2
        editor.nodes = [
            Node(
                x_start=w1_left,
                y_start=split_y,
                x_vector=w1_right - w1_left,
                y_vector=0,
                right_bbox_top=wall_bottom,
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=w1_left,
                right_bbox_right=w1_right,
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=wall_top,
                left_bbox_left=w1_left,
                left_bbox_right=w1_right,
                right_index=0x8000 | 4,
                left_index=0x8000 | 3,
            ),
            Node(
                x_start=w2_left,
                y_start=split_y,
                x_vector=w2_right - w2_left,
                y_vector=0,
                right_bbox_top=wall_bottom,
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=w2_left,
                right_bbox_right=w2_right,
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=wall_top,
                left_bbox_left=w2_left,
                left_bbox_right=w2_right,
                right_index=0x8000 | 6,
                left_index=0x8000 | 5,
            ),
            Node(
                x_start=w2_right,
                y_start=bounds["y_min"],
                x_vector=0,
                y_vector=bounds["y_max"] - bounds["y_min"],
                right_bbox_top=bounds["y_max"],
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=w2_right,
                right_bbox_right=bounds["x_max"],
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=bounds["y_min"],
                left_bbox_left=w2_left,
                left_bbox_right=w2_right,
                right_index=0x8000 | 2,
                left_index=1,
            ),
            Node(
                x_start=w2_left,
                y_start=bounds["y_min"],
                x_vector=0,
                y_vector=bounds["y_max"] - bounds["y_min"],
                right_bbox_top=bounds["y_max"],
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=w2_left,
                right_bbox_right=bounds["x_max"],
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=bounds["y_min"],
                left_bbox_left=w1_right,
                left_bbox_right=w2_left,
                right_index=2,
                left_index=0x8000 | 1,
            ),
            Node(
                x_start=w1_right,
                y_start=bounds["y_min"],
                x_vector=0,
                y_vector=bounds["y_max"] - bounds["y_min"],
                right_bbox_top=bounds["y_max"],
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=w1_right,
                right_bbox_right=bounds["x_max"],
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=bounds["y_min"],
                left_bbox_left=w1_left,
                left_bbox_right=w1_right,
                right_index=3,
                left_index=0,
            ),
            Node(
                x_start=w1_left,
                y_start=bounds["y_min"],
                x_vector=0,
                y_vector=bounds["y_max"] - bounds["y_min"],
                right_bbox_top=bounds["y_max"],
                right_bbox_bottom=bounds["y_min"],
                right_bbox_left=w1_left,
                right_bbox_right=bounds["x_max"],
                left_bbox_top=bounds["y_max"],
                left_bbox_bottom=bounds["y_min"],
                left_bbox_left=bounds["x_min"],
                left_bbox_right=w1_left,
                right_index=4,
                left_index=0x8000 | 0,
            ),
        ]

    reject_size = max(1, (len(editor.sectors) * len(editor.sectors) + 7) // 8)
    editor.reject = Lump(bytes(reject_size))
    editor.blockmap = Lump(build_blockmap(bounds, len(editor.linedefs)))

    wad = WAD(str(SOURCE_IWAD))
    wad.maps["E1M8"] = editor.to_lumps()
    wad.to_file(str(OUTPUT_IWAD))
    print(f"Wrote {OUTPUT_IWAD}")
def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Doom duel WAD assets from the ASCII map blueprint.")
    parser.add_argument("--svg-only", action="store_true", help="Only regenerate the tactical map SVG.")
    args = parser.parse_args()
    blueprint = load_geometry_blueprint("duel_e1m8")
    write_tactical_map_svg(blueprint)
    if not args.svg_only:
        build_wad(blueprint)


if __name__ == "__main__":
    main()
